codeargs:
  codepath: ./go/test
  ignoredirs:
    - ./go/test/ignore
  outputpath: /Users/haibei/study/gouml/test
goenv:
  gopath: /Users/haibei/go
runtime:
  path: ./runtime
  log:
    ext: log
    name: test
    path: /applogs
